<h3>Adicionar Usuários na Equipe</h3>  
<form action="<?= $this->url(array("controller" => "usuario", "action" => "adicionanaequipe"), null, true) ?>" method="post">
    <input name="idEquipe" value="<?php echo $this->equipe['EQ_ID'] ?>" type="hidden" />
    
    <?php echo "Equipe: ".$this->equipe['EQ_Nome'] ?>
    
    <select name="Usuario1">
        <?php foreach ($this->usuarios as $key => $usuario):
            ?>
            <option value="<?= $usuario['US_ID'] ?>"><?= $usuario['US_Nome'] ?></option>
            <?php
        endforeach;
        ?>
    </select>
    <input type="submit" value="Cadastrar" />
</form>