<h1>Nova Equipe</h1>
<hr/>
<div class="center-page">
    <form name="cadastrarEquipe" method="POST" action="<?=$this->url(array("controller"=>"equipe","action"=>"criar"),null,true)?>">
        <input name="PRJ_ID" type="hidden" value="<?=$cargo['CA_ID']?>">
        <input placeholder="Nome" name="EQ_Nome" type="text"/>
        <br/>
        <input placeholder="custo" name="EQ_CustoEquipe" type="number" step="any"/>
        <br/>
        <label class="label">Usuario:</label>
        <select name ="Usuario1">
            <?php foreach($this->usuarios as $key => $usuario):
            ?>
            <option value="<?=$usuario['US_ID']?>"><?=$usuario['US_Nome']?></option>

            <?php
            endforeach;
            ?>

        </select>
        <label>Projeto:</label>
        <select name ="Projeto">
            <?php foreach($this->projetos as $key => $usuario):
            ?>
            <option value="<?=$usuario['PRJ_ID']?>"><?=$usuario['PRJ_Nome']?></option>

            <?php
            endforeach;
            ?>
        </select>
        <br/>
        <input type="submit" value="Cadastrar" />
    </form>
</div>    
