<div id="welcome" class="center-page">
    <div id="titulo">
        <label id="BemVindo">Bem vindo ao Way</label>
    </div>   
    <hr/>
    <div class="caixa">
        <div class="circle"><h2>Missão</h2></div>        
        <p>
         O sistema Way ajuda você a concretizar suas ideias, permitindo que seu escopo seja feito de uma forma mais organizada, trazendo para si clientes mais satisfeitos.
        </p>
    </div>
    <div class="caixa">
        <div class="circle"><h2>Visão</h2></div>
        <p>
        Ser reconhecida como o melhor sistema de gerenciamento de escopo que oferece alto padrão de qualidade e total satisfação com seus clientes.
        </p>
    </div>
    <div class="caixa">
        <div class="circle"><h2>Valores</h2></div>
        <p>Ética e transparência;<br/>Respeito ao cliente;<br/>Comprometimento com inovação, robustez e eficiência;<br/>Quebrar paradigmas e estimular a criatividade</p>
    </div>
</div>