
<div id="welcome">
    <h1 class="bem-vindo">Bem vindo ao Way</h1>
    <h2 class="caixa"></h2>
    <p class="top"><h2>Missão</h2></p>
    <p>
    O sistema Way ajuda você a concretizar suas ideias, permitindo que seu escopo seja feito de uma forma mais organizada, assim seus clientes ficaram mais satisfeitos.
    </p>
    <p><h2>Visão </h2></p>
    <p>
    Ser reconhecida como o melhor sistema de gerenciamento de escopo que oferece alto padrão de qualidade e total satisfação com seus clientes.
    </p>
    <p><h2>Valores da empresa</h2></p>
    <ul>
        <li>Ética e transparência</li>
        <li>Respeito ao cliente</li>
        <li>Comprometimento com inovação, robustez e eficiência</li>
        <li>Quebrar paradigmas e estimular a criatividade</li>
    </ul>
</div>