<h2>Nova Categoria</h2>
<hr/>
<div class="center-page">  
    <form name="CadastraCategoria" method="POST" action="<?=$this->url(array("controller"=>"categoria","action"=>"criar"),null,true)?>">
        <input placeholder="Nome" name="CAT_Nome" type="text"/>
        <br/>
        <input placeholder="Descrição" name="CAT_Descricao" type="text"/>
        <br/>                      
        <input type="submit" value="Cadastrar"/>
    </form>
</div>    