<?= $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <base href="http://<?= $_SERVER['HTTP_HOST'] . $this->baseUrl() ?>/" />        
            <?php
            $this->headLink()->prependStylesheet('../public/css/icons.css');
            $this->headLink()->appendStylesheet('../public/css/login.css');
            $this->headLink()->appendStylesheet('../public/css/site.css');
            $this->headScript()->prependFile('../public/js/lib.js');
            $this->headScript()->appendFile('../public/js/login.js');

            echo $this->headLink() . "\n";
            echo $this->headScript() . "\n";
            ?> 

            <title>
                Projeto Way
            </title>
    </head>
    <body>
        <div class="menu">
            <ul>
                <li><a href="home.php"><strong>Projeto Way</strong></a></li>
                <span class="dividir"></span>		
                <li style="float:right;">
                    <div id="loginContainer">
                        <a href="#" id="loginButton"><span class="icon-user3"></span></a>
                        <div style="clear:both"></div>
                        <div id="loginBox">                
                            <form id="loginForm" action="home.php">
                                <fieldset id="body">										
                                    <a style="float:left;"  id="loginButton"><span class="icon-exit"></span></a>
                                    <a style="float:left;"<a href="<?=$this->url(array("controller"=>"admin","action"=>"logout"),null,true)?>" id="loginButton"><span class="icon-cog"></span></a>
                                    <!-- FECHAR SESSÃO AO SAIR -->
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </li>					
                <li style="float:right;"><a href="<?=$this->url(array("controller"=>"projeto","action"=>"novo"),null,true)?>"><span class="icon-file3"></span></a></li>			
                <li style="float:right;"><a href="<?=$this->url(array("controller"=>"admin","action"=>"index"),null,true)?>"><span class="icon-home"></span></a></li>
                <li style="float:right;"><a class="icon-users2" href="<?= $this->url(array("controller" => "equipe", "action" => "index"), null, true) ?>"></a></li>
                <li style="float:right;"><a class="icon-tags" href="<?= $this->url(array("controller" => "categoria", "action" => "novo"), null, true) ?>"></a></li>
            </li>
            </ul>
        </div>
        <div id="conteudo">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="rodape">
            <p> Copyright @ 2014 - Sistema Way - Desenvolvido por EasyTec</p>
        </div>
    </body>
</html>	