<br /><br />
<div class="caixa_descricao" id="projeto_index">
    <h4>Descrição</h4><hr/>
    <label>Nome.: </label><br/><br/>     
    <label>Descrição.: </label><br/><br/> 
    <label>Gerente.: </label><br/><br/> 
    <label>Equipe.: </label><br/><br/> 
    <label>Recurso.: </label><br/><br/> 
    <label>Requisitos.: </label><br/><br/> 
    <label>Prazo.:</label><br/><br/> 
    <label>Custo.:</label><br/><br/> 
</div>
<div class="caixa_descricao" id="projeto_index">
    <h4>Membros</h4><hr/>

</div>